# Какое время должен провести игрок на сервере, что бы смог писать в чат
sec-need-time: 900
# Какое сообщение выводится если игрок пишет в чат и не наиграл нужное кол-во времени
message: "&cОШИБКА: &4&lВы не отыграли на сервере &4&l15 минут!"